import { useMemo, useRef, useState } from "react";
import { Streamdown } from "streamdown";
import { trpc } from "@/lib/trpc";
import { ArrowLeft, Check, ChevronRight, CircleAlert, FileText, MessageCircle, Paperclip, Search, Send, ShieldCheck, Sparkles, Upload, X } from "lucide-react";

const money = (value: number) => `₹${Math.round(value).toLocaleString("en-IN")}`;

type Props = { onClose: () => void };

type DocMessage = { role: "user" | "assistant"; content: string; source?: string };
type LocalDocument = { id: string; name: string; size: string; pages: number; type: string; uploadedAt: string; period: string; status: string; summary: any };

export default function DocumentReview({ onClose }: Props) {
  const { data, isLoading } = trpc.finance.documents.useQuery();
  const documentAsk = trpc.finance.documentAsk.useMutation();
  const registerDocument = trpc.finance.registerDocument.useMutation();
  const utils = trpc.useUtils();
  const [selectedId, setSelectedId] = useState("doc_august_2026");
  const [question, setQuestion] = useState("");
  const fileRef = useRef<HTMLInputElement>(null);
  const [messages, setMessages] = useState<DocMessage[]>([{ role: "assistant", content: "I’ve processed the complete August statement. Ask me anything about balances, spending, recurring payments, or specific transactions.", source: "Pages 1–6 · Grounded in active PDF" }]);
  const libraryDocs: LocalDocument[] = (data?.documents ?? []) as LocalDocument[];
  const document = libraryDocs.find(item => item.id === selectedId) ?? libraryDocs[0];
  const s = document?.summary;
  const quickPrompts = ["What was my biggest transaction?", "How much did I spend on shopping?", "Were there any unusual transactions?"];
  const previewLines = useMemo(() => ["HDFC BANK", "Statement of Account", "01 Aug 2026 — 31 Aug 2026", "Account •• 4821", "", "Opening balance              ₹6,12,400.00", "Salary credit                 ₹2,38,000.00", "Rent · Koramangala             -₹42,000.00", "Groww SIP · Index fund          -₹25,000.00", "Amazon India                   -₹12,480.00", "Vistara                        -₹18,400.00", "Closing balance                ₹5,84,200.00"], []);

  const ask = async (text = question) => {
    const trimmed = text.trim(); if (!trimmed || !document || documentAsk.isPending) return;
    const next = [...messages, { role: "user" as const, content: trimmed }]; setMessages(next); setQuestion("");
    try {
      const response = await documentAsk.mutateAsync({ documentId: document.id, question: trimmed, history: messages.slice(-8).map(({ role, content }) => ({ role, content })) });
      setMessages([...next, { role: "assistant", content: response.answer, source: response.source }]);
    } catch { setMessages([...next, { role: "assistant", content: "I couldn’t reach document intelligence right now. Please try again." }]); }
  };

  if (isLoading || !document) return <div className="doc-overlay"><div className="doc-loading"><Sparkles size={22} /><p>Loading document intelligence…</p></div></div>;
  if (!s) return <div className="doc-overlay"><div className="doc-loading"><div className="upload-icon"><Sparkles size={22} /></div><h2>{document.name}</h2><p>Processing the complete PDF before showing any summary or answers.</p><small>Uploading → Extracting → Analyzing</small><button className="secondary-btn" onClick={onClose}>Back to workspace</button></div></div>;
  const handleUpload = async (file?: File) => { if (!file || registerDocument.isPending) return; const id = `doc_${crypto.randomUUID()}`; setSelectedId(id); setMessages([{ role: "assistant", content: "Uploading → Processing → Extracting → Analyzing this statement…", source: `Active document ID: ${id}` }]); try { await registerDocument.mutateAsync({ id, name: file.name, size: `${Math.max(1, Math.round(file.size / 1024))} KB` }); await utils.finance.documents.invalidate(); } catch { setMessages([{ role: "assistant", content: "Unable to process this statement. The previous documents remain available. Please try again.", source: "Processing error" }]); } };
  return <div className="doc-overlay">
    <header className="doc-topbar"><button className="doc-back" onClick={onClose}><ArrowLeft size={16} /> Back to workspace</button><div className="doc-brand"><span className="doc-brand-mark"><Sparkles size={13} /></span><b>CredWise Document Intelligence</b><span className="doc-secure"><ShieldCheck size={13} /> Private analysis</span></div><button className="icon-btn" onClick={onClose}><X size={19} /></button></header>
    <div className="doc-layout">
      <aside className="doc-library"><div className="doc-library-head"><div><p className="eyebrow">DOCUMENT LIBRARY</p><h2>My documents</h2></div><button className="doc-upload-btn" onClick={() => fileRef.current?.click()}><Upload size={15} /> Upload another</button><input ref={fileRef} hidden type="file" accept=".pdf" onChange={e => handleUpload(e.target.files?.[0])} /></div>{libraryDocs.map(item => <button className={`doc-item ${item.id === selectedId ? "selected" : ""}`} key={item.id} onClick={() => { setSelectedId(item.id); setMessages([{ role: "assistant", content: `I’m ready to answer questions about ${item.name}.`, source: item.status === "Ready for review" ? "Pages 1–6 · Grounded in active PDF" : "Active document · Processing" }]); }}><div className="doc-file-icon"><FileText size={17} /></div><div><b>{item.name.replace(".pdf", "")}</b><span>{item.type} · {item.period}</span><small><i /> {item.status}</small></div><ChevronRight size={15} /></button>)}<div className="doc-library-foot"><ShieldCheck size={15} /><span>Documents are analyzed securely.<br /><b>Nothing is added to your profile without confirmation.</b></span></div></aside>
      <main className="doc-main"><div className="doc-heading"><div><p className="eyebrow mint-eyebrow"><FileText size={12} /> DOCUMENT REVIEW</p><h1>{document.name}</h1><p>Uploaded {document.uploadedAt} · {document.pages} pages · {document.size}</p></div><div className="doc-ready"><Check size={14} /> Analysis complete</div></div><div className="doc-content-grid">
        <section className="doc-summary"><div className="summary-header"><div><p className="eyebrow">AUTOMATIC FULL DOCUMENT SUMMARY</p><h2>Statement overview</h2></div><span className="source-chip"><ShieldCheck size={12} /> Grounded in PDF</span></div><div className="overview-grid"><div><span>Institution</span><b>{s.institution}</b><small>{s.account}</small></div><div><span>Statement period</span><b>{document.period}</b><small>{s.transactionCount} transactions</small></div><div><span>Opening balance</span><b>{money(s.openingBalance)}</b><small>Source: Page 1</small></div><div><span>Closing balance</span><b>{money(s.closingBalance)}</b><small className="negative-text">−₹28,200 net movement</small></div></div><div className="summary-section"><h3>Money in & money out</h3><div className="in-out-grid"><div><div className="summary-number in">{money(s.totalCredits)}</div><span>Total credits</span><div className="summary-bar"><i style={{ width: "89%" }} /></div><small>Salary received · {money(s.totalCredits)}</small></div><div><div className="summary-number out">{money(s.totalDebits)}</div><span>Total debits</span><div className="summary-bar out"><i style={{ width: "100%" }} /></div><small>Across {s.transactionCount} transactions</small></div></div></div><div className="summary-section"><div className="section-title-inline"><h3>Spending breakdown</h3><span>Identified categories · Pages 2–5</span></div><div className="category-list">{s.categories.map((category: any) => <div className="category-row" key={category.name}><span><i className="category-dot" />{category.name}</span><div className="category-track"><i style={{ width: `${category.share * 4.7}%` }} /></div><b>{money(category.amount)}</b><small>{category.share}%</small></div>)}</div></div><div className="summary-split"><div className="summary-section compact"><h3>Largest transaction</h3><div className="largest-card"><CircleAlert size={17} /><div><b>{s.largestTransaction}</b><span>Source: Page 2 · Transaction table</span></div></div></div><div className="summary-section compact"><h3>Recurring payments</h3><div className="recurring-list">{s.recurring.slice(0, 3).map((item: any) => <span key={item}><i />{item}</span>)}</div></div></div><div className="takeaway-box"><div className="takeaway-icon"><Sparkles size={16} /></div><div><p className="eyebrow mint-eyebrow">KEY TAKEAWAYS</p>{s.takeaways.map((item: any) => <p key={item}>• {item}</p>)}</div></div></section>
        <aside className="doc-side"><div className="pdf-card"><div className="pdf-card-head"><span><FileText size={14} /> PDF PREVIEW</span><span>{document.pages} pages</span></div><div className="pdf-paper"><div className="pdf-logo">HDFC BANK</div>{previewLines.map((line, index) => <div className={`pdf-line ${index === 0 ? "title" : index === 1 ? "sub" : line.includes("₹") ? "amount" : ""}`} key={`${line}-${index}`}>{line || " "}</div>)}<div className="pdf-fade">Showing page 1 of {document.pages}</div></div><button className="preview-btn">Open full PDF <ChevronRight size={14} /></button></div><div className="processing-card"><div className="processing-head"><span><Sparkles size={14} /> PROCESSING DETAILS</span><span className="confidence">94% confidence</span></div><div className="processing-row"><Check size={14} /> Full document extracted <small>{document.pages}/{document.pages} pages</small></div><div className="processing-row"><Check size={14} /> Transactions categorized <small>42 found</small></div><div className="processing-row"><Check size={14} /> Patterns identified <small>8 signals</small></div><div className="processing-row"><Check size={14} /> Ready for questions <small>Now</small></div></div></aside>
      </div></main>
    </div>
    <section className="doc-chat"><div className="doc-chat-inner"><div className="doc-chat-head"><div><p className="eyebrow mint-eyebrow"><MessageCircle size={12} /> CREDWISE DOCUMENT INTELLIGENCE</p><h2>Ask anything about this document</h2></div><span><i /> Active context · {document.name.replace(".pdf", "")}</span></div><div className="doc-chat-messages">{messages.map((message, index) => <div className={`chat-message ${message.role}`} key={`${message.role}-${index}`}><div className={`chat-avatar ${message.role}`}>{message.role === "assistant" ? <Sparkles size={14} /> : "AM"}</div><div className="chat-bubble"><Streamdown>{message.content}</Streamdown>{message.source && <span className="chat-source"><ShieldCheck size={11} /> {message.source}</span>}</div></div>)}{documentAsk.isPending && <div className="chat-message assistant"><div className="chat-avatar assistant"><Sparkles size={14} /></div><div className="chat-bubble typing"><i /><i /><i /></div></div>}</div><div className="doc-prompt-row">{quickPrompts.map(prompt => <button key={prompt} onClick={() => ask(prompt)}>{prompt}</button>)}</div><div className="doc-input-row"><Paperclip size={16} /><input value={question} onChange={e => setQuestion(e.target.value)} onKeyDown={e => e.key === "Enter" && ask()} placeholder="Ask a question about this PDF…" /><button className="send-btn" disabled={!question.trim() || documentAsk.isPending} onClick={() => ask()}><Send size={15} /></button></div><div className="doc-disclaimer"><ShieldCheck size={12} /> Answers are grounded in the active document. If information is unavailable, CredWise will say so.</div></div></section>
  </div>;
}
